//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/workspaces/compilers/cspg/Grammer.ParserGenerator/Interperter.ExodiaLang\Exodia.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ExodiaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IExodiaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ExodiaParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ExodiaParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.class_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_declaration([NotNull] ExodiaParser.Class_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.class_extends"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass_extends([NotNull] ExodiaParser.Class_extendsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_statement([NotNull] ExodiaParser.Iteration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_statement([NotNull] ExodiaParser.For_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.do_while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDo_while_statement([NotNull] ExodiaParser.Do_while_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_statement([NotNull] ExodiaParser.While_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.variable_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_statement([NotNull] ExodiaParser.Variable_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.variable_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration_list([NotNull] ExodiaParser.Variable_declaration_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] ExodiaParser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.variable_initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initializer([NotNull] ExodiaParser.Variable_initializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] ExodiaParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.empty_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmpty_statement([NotNull] ExodiaParser.Empty_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] ExodiaParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.block_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statement([NotNull] ExodiaParser.Block_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_declaration([NotNull] ExodiaParser.Function_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter_list([NotNull] ExodiaParser.Formal_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] ExodiaParser.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] ExodiaParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_expression([NotNull] ExodiaParser.Assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] ExodiaParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.left_hand_side_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeft_hand_side_expression([NotNull] ExodiaParser.Left_hand_side_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.member_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_expression([NotNull] ExodiaParser.Member_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.this_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThis_expression([NotNull] ExodiaParser.This_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] ExodiaParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.logical_OR_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_OR_expression([NotNull] ExodiaParser.Logical_OR_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.logical_AND_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_AND_expression([NotNull] ExodiaParser.Logical_AND_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality_expression([NotNull] ExodiaParser.Equality_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.relational_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_expression([NotNull] ExodiaParser.Relational_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.additive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditive_expression([NotNull] ExodiaParser.Additive_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.multiplicative_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicative_expression([NotNull] ExodiaParser.Multiplicative_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] ExodiaParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_expression([NotNull] ExodiaParser.Call_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.super"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuper([NotNull] ExodiaParser.SuperContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.callee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallee([NotNull] ExodiaParser.CalleeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] ExodiaParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument_list([NotNull] ExodiaParser.Argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.new_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_expression([NotNull] ExodiaParser.New_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] ExodiaParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesized_expression([NotNull] ExodiaParser.Parenthesized_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>atom</c>
	/// labeled alternative in <see cref="ExodiaParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] ExodiaParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.true_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrue_literal([NotNull] ExodiaParser.True_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.false_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFalse_literal([NotNull] ExodiaParser.False_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] ExodiaParser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ExodiaParser.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_literal([NotNull] ExodiaParser.String_literalContext context);
}
