//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/workspaces/compilers/cspg/Grammer.ParserGenerator/Interperter.Kaleidoscope/Kaleidoscope.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="KaleidoscopeParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IKaleidoscopeVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] KaleidoscopeParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] KaleidoscopeParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] KaleidoscopeParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.external"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal([NotNull] KaleidoscopeParser.ExternalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrototype([NotNull] KaleidoscopeParser.PrototypeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>continuedBinaryExpression</c>
	/// labeled alternative in <see cref="KaleidoscopeParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinuedBinaryExpression([NotNull] KaleidoscopeParser.ContinuedBinaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>finalBinaryExpression</c>
	/// labeled alternative in <see cref="KaleidoscopeParser.binaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinalBinaryExpression([NotNull] KaleidoscopeParser.FinalBinaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>callExpression</c>
	/// labeled alternative in <see cref="KaleidoscopeParser.identifierExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallExpression([NotNull] KaleidoscopeParser.CallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableExpression</c>
	/// labeled alternative in <see cref="KaleidoscopeParser.identifierExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableExpression([NotNull] KaleidoscopeParser.VariableExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.numberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberExpression([NotNull] KaleidoscopeParser.NumberExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.parenExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpression([NotNull] KaleidoscopeParser.ParenExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="KaleidoscopeParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] KaleidoscopeParser.PrimaryContext context);
}
